language: java

script:
  - ./gradlew build

  - cd ${TRAVIS_BUILD_DIR}/junit4/
  - mvn test
#  - ant test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter/
  - mvn test

  - cd ${TRAVIS_BUILD_DIR}/junit-jupiter-params/
  - mvn test

jdk:
  - oraclejdk8

dist: precise

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - ./gradlew jacocoTestReport coveralls

sudo: false
